# Generated by Django 4.2.1 on 2023-05-25 02:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('street', models.CharField(blank=True, max_length=64, null=True)),
                ('district', models.CharField(blank=True, max_length=64, null=True)),
                ('number', models.CharField(blank=True, max_length=12, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('cost', inventory.models.CurrencyField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recipe', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.productmenu')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_amount', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('sub_total', inventory.models.CurrencyField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.order')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.productoption')),
            ],
        ),
        migrations.AddField(
            model_name='productmenu',
            name='products',
            field=models.ManyToManyField(through='delivery.ProductOption', to='delivery.product'),
        ),
        migrations.CreateModel(
            name='ProductCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_amount', models.PositiveSmallIntegerField()),
                ('discount', models.DecimalField(decimal_places=2, default='0.00', max_digits=5)),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_main_products', to='delivery.product')),
                ('sub_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_sub_products', to='delivery.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='combo',
            field=models.ManyToManyField(blank=True, through='delivery.ProductCombo', to='delivery.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.productmenu'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_orders',
            field=models.ManyToManyField(through='delivery.ProductOrder', to='delivery.productoption'),
        ),
    ]
